# =============================================================================
# FacultyIQ - Academic Research Analytics Dashboard
# =============================================================================
#
# A Shiny application for analyzing academic division research productivity
# and impact metrics using OpenAlex, Scopus, and Google Scholar data.
#
# Author: Generated by Claude
# License: MIT
#
# To run: shiny::runApp()
# Or in RStudio: Click "Run App" button
# =============================================================================

# Load global configuration and dependencies
source("global.R")

# =============================================================================
# UI Definition
# =============================================================================

ui <- shinydashboard::dashboardPage(
  skin = "blue",

  # Header
  shinydashboard::dashboardHeader(
    title = app_config$app_title %||% "FacultyIQ",
    titleWidth = 300,

    # Notification dropdown showing data source status
    shinydashboard::dropdownMenu(
      type = "notifications",
      icon = shiny::icon("database"),
      badgeStatus = NULL,
      headerText = "Data Source Status",

      shinydashboard::notificationItem(
        text = "OpenAlex: Available (Free)",
        icon = shiny::icon("check-circle"),
        status = "success"
      ),
      shinydashboard::notificationItem(
        text = if (scopus_configured) "Scopus: Configured" else "Scopus: Not configured",
        icon = shiny::icon(if (scopus_configured) "check-circle" else "exclamation-circle"),
        status = if (scopus_configured) "success" else "warning"
      ),
      shinydashboard::notificationItem(
        text = if (requireNamespace("scholar", quietly = TRUE))
          "Google Scholar: Available" else "Google Scholar: Not installed",
        icon = shiny::icon(if (requireNamespace("scholar", quietly = TRUE))
                            "check-circle" else "exclamation-circle"),
        status = if (requireNamespace("scholar", quietly = TRUE)) "success" else "warning"
      )
    )
  ),

  # Sidebar
  shinydashboard::dashboardSidebar(
    width = 250,

    shinydashboard::sidebarMenu(
      id = "sidebar_menu",

      shinydashboard::menuItem(
        "Data Upload & Validation",
        tabName = "upload",
        icon = shiny::icon("upload")
      ),

      shinydashboard::menuItem(
        "Identity Resolution",
        tabName = "resolution",
        icon = shiny::icon("user-check")
      ),

      shinydashboard::menuItem(
        "Division Dashboard",
        tabName = "dashboard",
        icon = shiny::icon("chart-line")
      ),

      shinydashboard::menuItem(
        "Individual Profiles",
        tabName = "profiles",
        icon = shiny::icon("user")
      ),

      shinydashboard::menuItem(
        "Data Export",
        tabName = "export",
        icon = shiny::icon("download")
      ),

      shinydashboard::menuItem(
        "Rank Prediction",
        tabName = "prediction",
        icon = shiny::icon("graduation-cap")
      ),

      shinydashboard::menuItem(
        "Compare & Analyze",
        tabName = "comparison",
        icon = shiny::icon("balance-scale")
      ),

      shiny::hr(),

      # Data completeness indicator
      shiny::div(
        style = "padding: 10px;",
        shiny::uiOutput("sidebar_status")
      )
    )
  ),

  # Body
  shinydashboard::dashboardBody(
    # Custom CSS
    shiny::tags$head(
      shiny::tags$style(HTML("
        .content-wrapper { background-color: #f4f6f9; }
        .box { border-radius: 5px; }
        .info-box { border-radius: 5px; }
        .nav-tabs-custom > .nav-tabs > li.active {
          border-top-color: #3c8dbc;
        }
        .well { background-color: #ffffff; }
        .alert { border-radius: 4px; }
        .btn-primary { background-color: #3c8dbc; border-color: #367fa9; }
        .btn-success { background-color: #00a65a; border-color: #008d4c; }
        .progress-bar { background-color: #3c8dbc; }
        .dataTables_wrapper { font-size: 13px; }
        .sparkline { display: inline-block; }
      "))
    ),

    shinydashboard::tabItems(
      # Tab 1: Upload
      shinydashboard::tabItem(
        tabName = "upload",
        shiny::fluidRow(
          shiny::column(
            width = 12,
            shiny::h2("Data Upload & Validation"),
            shiny::p(
              "Upload your faculty roster file (CSV or Excel) containing names,",
              "academic ranks, and external identifiers (Scopus ID, Google Scholar ID)."
            )
          )
        ),
        mod_upload_ui("upload")
      ),

      # Tab 2: Resolution
      shinydashboard::tabItem(
        tabName = "resolution",
        shiny::fluidRow(
          shiny::column(
            width = 12,
            shiny::h2("Identity Resolution"),
            shiny::p(
              "Map roster entries to unique author identifiers in OpenAlex.",
              "Automatic resolution uses Scopus IDs; manual resolution allows",
              "searching and selecting the correct author."
            )
          )
        ),
        mod_resolution_ui("resolution")
      ),

      # Tab 3: Dashboard
      shinydashboard::tabItem(
        tabName = "dashboard",
        shiny::fluidRow(
          shiny::column(
            width = 12,
            shiny::h2("Division Dashboard"),
            shiny::p(
              "Aggregate metrics and trends for your division.",
              "Filter by year range, academic rank, or specific individuals."
            )
          )
        ),
        mod_dashboard_ui("dashboard")
      ),

      # Tab 4: Profiles
      shinydashboard::tabItem(
        tabName = "profiles",
        shiny::fluidRow(
          shiny::column(
            width = 12,
            shiny::h2("Individual Profiles"),
            shiny::p(
              "Detailed metrics and publication history for individual faculty members."
            )
          )
        ),
        mod_profile_ui("profiles")
      ),

      # Tab 5: Export
      shinydashboard::tabItem(
        tabName = "export",
        shiny::fluidRow(
          shiny::column(
            width = 12,
            shiny::h2("Data Export"),
            shiny::p(
              "Export your data, metrics, and visualizations."
            )
          )
        ),
        mod_export_ui("export")
      ),

      # Tab 6: Rank Prediction
      shinydashboard::tabItem(
        tabName = "prediction",
        shiny::fluidRow(
          shiny::column(
            width = 12,
            shiny::h2("Faculty Rank Prediction"),
            shiny::p(
              "Predict appropriate faculty ranks based on research metrics",
              "and identify promotion candidates by comparing metrics to",
              "benchmarks from similar faculty."
            )
          )
        ),
        mod_prediction_ui("prediction")
      ),

      # Tab 7: Compare & Analyze
      shinydashboard::tabItem(
        tabName = "comparison",
        shiny::fluidRow(
          shiny::column(
            width = 12,
            shiny::h2("Compare & Analyze"),
            shiny::p(
              "Compare faculty members side-by-side, analyze career trajectories,",
              "view division rankings, and identify faculty who may need support."
            )
          )
        ),
        mod_comparison_ui("comparison")
      )
    )
  )
)

# =============================================================================
# Server Definition
# =============================================================================

server <- function(input, output, session) {

  # ---------------------------------------------------------------------------
  # Initialize Modules
  # ---------------------------------------------------------------------------

  # Upload module returns roster data
  upload_rv <- mod_upload_server("upload")

  # Resolution module receives roster, returns resolved data
  resolution_rv <- mod_resolution_server("resolution", upload_rv)

  # Dashboard module receives both
  mod_dashboard_server("dashboard", resolution_rv, upload_rv)

  # Profile module
  mod_profile_server("profiles", resolution_rv, upload_rv)

  # Export module
  mod_export_server("export", resolution_rv, upload_rv)

  # Prediction module
  mod_prediction_server("prediction", resolution_rv, roster_rv = upload_rv)

  # Comparison module
  mod_comparison_server("comparison", resolution_rv, roster_rv = upload_rv)

  # ---------------------------------------------------------------------------
  # Sidebar Status
  # ---------------------------------------------------------------------------

  output$sidebar_status <- shiny::renderUI({
    if (is.null(upload_rv$roster)) {
      return(shiny::div(
        class = "text-muted",
        shiny::icon("info-circle"),
        " No data loaded"
      ))
    }

    n_roster <- nrow(upload_rv$roster)

    n_resolved <- if (!is.null(resolution_rv$resolution_df)) {
      sum(resolution_rv$resolution_df$resolution_status %in% c("resolved", "manual"), na.rm = TRUE)
    } else {
      0
    }

    n_with_data <- if (!is.null(resolution_rv$person_data)) {
      sum(sapply(resolution_rv$person_data, function(x) length(x$data_sources) > 0))
    } else {
      0
    }

    shiny::div(
      shiny::p(
        shiny::icon("users"),
        sprintf(" %d faculty loaded", n_roster)
      ),
      shiny::p(
        shiny::icon("user-check"),
        sprintf(" %d resolved", n_resolved)
      ),
      shiny::p(
        shiny::icon("database"),
        sprintf(" %d with data", n_with_data)
      )
    )
  })

  # ---------------------------------------------------------------------------
  # Navigation Logic
  # ---------------------------------------------------------------------------

  # When user clicks "Proceed" in upload module, switch to resolution tab
  shiny::observeEvent(upload_rv$proceed, {
    if (isTRUE(upload_rv$proceed)) {
      shinydashboard::updateTabItems(session, "sidebar_menu", "resolution")
      upload_rv$proceed <- FALSE
    }
  })

  # ---------------------------------------------------------------------------
  # Global Error Handling
  # ---------------------------------------------------------------------------

  # Catch unhandled errors and show notification
  options(shiny.error = function() {
    err <- geterrmessage()
    shiny::showNotification(
      paste("An error occurred:", err),
      type = "error",
      duration = 10
    )
  })

  # ---------------------------------------------------------------------------
  # Session Cleanup
  # ---------------------------------------------------------------------------

  session$onSessionEnded(function() {
    # Clean up expired cache on session end
    cache_clear_expired(expiry_days = app_config$cache_expiry_days %||% 7)
  })
}

# =============================================================================
# Run Application
# =============================================================================

shinyApp(ui = ui, server = server)
